### ISSUE TITLE
preprocessReads: object 'i' does not exist

### ISSUE THREAD

**Issue by talrax1** [tgirke/systemPipeR#74]
I'm a little inexperienced so I may not write all of this correctly but it appears that the preprocessReads function contains an error on lines 21 and 22. They both contain an i but are not in a loop. So the function breaks when doing paired end reads with the args object.

Relevant section shown below with i's in bold and with spaces around them.

```r
 if (!is.null(args)) {
    if (all(!inherits(args, "SYSargs") & !inherits(args, 
                                                   "SYSargs2"))) 
      stop("Argument 'args' needs to be assigned an object of class 'SYSargs' OR 'SYSargs2")
    if (class(args) == "SYSargs") {
      colnames_args <- colnames(targetsout(args))
      targets_in <- targetsin(args)
      if (!all(c("FileName1", "FileName2") %in% colnames_args)) {
        outpaths <- outpaths(args)
      }
      else {
        outpaths1 <- as.character(targetsout(args)$FileName1 [I] ) # here
        outpaths2 <- as.character(targetsout(args)$FileName2 [I] ) # and here
      }
    }
```
When run, this will return: error object 'i' does not exist

After removing the [i]'s and recompiling the function, it seems to work properly again.

**Comment by lz100** [comment]
@tgirke Do you want me to submit a pull request or you can quickly remove the `[i]` in line [489, 490](https://github.com/tgirke/systemPipeR/blob/8a85df5e1dc71dcee208133efad57ce47ab2cee9/R/utilities.R#L489)?

This bug is in the legacy `SYSargs` class object which we do not use anymore so no one tested it in recent year(s). I think this happened when Dani upgraded `SYSargs` to `SYSargsList` and directly copied code from somewhere below in the for loop, but here as talrax1 mentioned, is not in a loop. 

Just checked the release history, this bug was there since [3_14](https://github.com/tgirke/systemPipeR/blob/RELEASE_3_14/R/utilities.R#L489)

**Comment by lz100** [comment]
Thanks @talrax1, the bug has been fixed on the master, try to install the Github version, it should work now.
